project:
  type: website
  output-dir: _site

execute:
  eval: false

ipynb-filters:
  - 6_filter/filter.py

website:
  page-navigation: true
  repo-actions: [edit, issue]
  title: "Quarto for Python devs"
  description: "Posit::Conf 2023"
  repo-url: https://github.com/hamelsmu/posit-python-quarto
  page-footer:
    left: "&copy; Copyright 2023, Hamel Husain"
    center:
      - icon: github
        href: https://github.com/orgs/hamelsmu
    right: "This page is built with 💛 and [Quarto](https://quarto.org/)."

  open-graph: true
  sidebar:
    pinned: true
    align: center
    style: docked
    search: true
    collapse: false
    contents: 
      - index.qmd
      - text: Setup
        href: 1_setup/index.qmd
      - text: Intro
        href: 2_intro/index.qmd
      - text: Basics
        href: 3_basics/index.qmd
      - text: Config & Options
        href: 4_config/index.qmd
      - text: Publishing
        href: 5_publishing/index.qmd
      - text: Nb Filters & Render Scripts
        href: 6_filter/index.qmd

format:
  html:
    code-copy: true
    theme: cosmo
    css: styles.css
    toc: true
    
