---
title: "Quarto For Python Devs"
subtitle: "Posit::Conf 2023"
format:
  html:
    toc: true
---


> 9:00 AM - 5:00 PM CDT
> Monday, Sep 18, 2023

Sharing knowledge through writing is a critical aspect of scientific activity, including data science. It allows researchers to communicate their findings and insights to a wider audience, build upon existing work, and collaborate with others in their field. However, until recently, there have been limited options for publishing long-form writing and expository analyses authored in Jupyter Notebooks, a popular medium for data scientists.

Enter Quarto - an innovative, open-source scientific and technical publishing system compatible with Jupyter Notebooks and other popular mediums. Quarto provides data scientists with a seamless way to publish their work in a high-quality format that is easily accessible and shareable. With Quarto, researchers can turn their Jupyter Notebooks into professional-looking publications in a variety of formats, including web pages, books, and slides.

In this workshop, we will demonstrate how Quarto enables data scientists to turn their work products into professional, high-quality websites, blog posts, and other shareable artifacts. As a bonus, we will also discuss how you can create and document Python packages using Jupyter Notebooks and Quarto with the help of nbdev.

### In the Morning

#### Core Quarto

| Time          | Module                              |
|---------------|-------------------------------------|
| 9:00 - 09:15   | [Quarto Setup](1_setup/)   |
| 9:15 - 09:40   | [Intro](2_intro)   |
| 9:40 - 10:10   | [Quarto Basics](3_basics/)   |
| 10:10 - 10:30  | [Configuration & Options Part 1](4_config/)         |
| 10:30 - 11:00   | 30 min break                               |
| 11:00 - 11:15  | [Configuration & Options Part 2](4_config/)         |
| 11:15 - 11:30  |  15 min lab break / try stuff                    |
| 11:30 - 11:45  | [Publishing](5_publishing/)         |
| 11:45 - 12:00  |  [Notebook Filters & Render Scripts](6_filter/)      |
| 12:00 - 1:15  |  Lunch                        |

### In the Afternoon

#### Quarto-Python Ecosystem

| Time        | Module                                        |
|-------------|-----------------------------------------------|
| 1:15 - 1:40 | [nbdev](7_nbdev/) w/Hamel Husain | 
| 1:40 - 1:50 | 10 min break                                  |
| 1:50 - 2:40 | [ShinyLive For Python](https://shiny.posit.co/py/docs/shinylive.html) w/Gordon Shotwell |
| 2:40 - 3:00 | 20 min break                                   |
| 3:00 - 3:30 | [Slides in Quarto](8-slides/) w/ Emil Hansen   |
| 3:30 - 3:40 | 10 min break                           |
| 3:40 - 4:20 | [Quartodoc](https://github.com/machow/quartodoc) w/Michael Chow              |
| 4:20 - 4:30 | 10 min break                           |
| 4:30 - 5:00 | Q&A With Quarto Team (move rooms)      |


## Instructor

Hamel is a founder at [Parlance](https://parlance-labs.com), a research lab and consultancy focused on large language models. Prior to Parlance, Hamel was a machine learning engineer at companies like Airbnb, GitHub, and DataRobot. You can find more about Hamel on his [personal site](https://hamel.dev/).