name: pub
on: 
    push:
        branches: main

jobs:
    pub:
        runs-on: ubuntu-latest
        steps:
        - name: Check out repository
          uses: actions/checkout@v4
        - name: setup Python
          uses: actions/setup-python@v3
        - name: install Jupyter
          run: python3 -m pip install jupyter
        - name: Install Quarto
          uses: quarto-dev/quarto-actions/setup@v2
        - name: Publish to GitHub Pages (and render)
          uses: quarto-dev/quarto-actions/publish@v2
          with:
            target: gh-pages
